apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/erezshi/argocd-demo-app.git
    path: .
    targetRevision: HEAD
    helm:
      valueFiles:
        - apps/airflow/airflow-values.yaml
      chart: airflow
      releaseName: airflow
      repo: https://airflow.apache.org
      targetRevision: 1.15.0
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
