---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgBqcsHiWYbEfPOJI3B7IUvwKltdfYsXa5T/AwoNTALq0iGiF14TcvekbRM8zqJjev3J2hDPJNq9s4LUis68xZww8CHDSr0kVREEIbOrZwBOi+1xkibZgWj3i4OoSMEH/zU4BGZt7/Y4933GMrdF9DAzkgAhOqBni2yeM8oy3xvY9njca9PjdoXWScgDLN5BvFCjbT/jUW6repatZutFKbRHbw3FNDS1l4p7ErOSPxkO1NnA8ggAfsxRjRy8/unqrwB7TKjv1JbdngxCYQ9s/RMNzJLsePBV5BCJodQ/2XsPF2Lrlx4xIxP9/WO5KPJfD7KKhdKinl1nsoXOo0e0b0V2Ckc8JaCn8StbN7FjlCV06McTch/MbDBmdV+HR4i77AA5U5G0AYpPq26bCwMmC9y/+zR+oGFh/IrkSqsKVD0eGPbv4Ti62kcEo3Sm6IYYUmL7qqYmiNAHQ1zQqRP83AiynyLp1eABa6cIJFohPdhuNziNRU+hXyv20OvWTHnODGQ1WonnqTgrdfKxvERsjVgzHHV3xl0JXFoNgFw5Zk0v68L8ITcHmdMchW1+4PHWc1S4N8BNiXolk+GJNReDwGJF+Rnp9RlNqpVamCqSHNHfU1/WhCMGvpdVy8+fJj5oY9sClqFym3eJrP3yEvJHeGPArXVxuosMVozw7nz8S8O+gp5meSpASNJDj/86Nyub756o0rCEfeg=
    username: AgAzON4abSNpuO6/HFEye+cSO8woFVYFR6CX0nj9G8h7aZT75K6NzTvJ2Bk4LS86t1OROM9ZM5cq82xaRmekd03gAhXGOpA9Wdb0R/4zLocdytRXnFaBpwveTCP/cB7h64d2WLnov1IIfxnePjAqeUtzxyfnD7RoKXHeFOJYt+A/jtSDQVBKb/UIyoV9HRtTxfNESkInTjzL7arq/t/9/fG7M8k45e975UzTVGAVuChdRwyvtpvqwYQzihHjep4JTflYX8iXYGzECCyFoZl1VCRhnSeEQP5Ylkv8uKLyojERHpjmkPCbaIyYX3vFslJhfs/35nRMweZbAhd6JgRPVQoGBBGRSH+CAlBpagE2jc3gvSKn94Ln6VI4NwlRK0MEnGm/fyVR8epGwmqp6Xm8+u/yAqwEd80niEdZmeOhZqth2A3i4d68E1ipOyV34p1xY1EIHvfR9Ld6zLX+hnZyc5PjmPM7AfNla4m381erEaLjKRMPRCds9pr2jptBBSRbEFHjf5PlUGNKeajxGpuO/gxynK4HtAxIs+l6QZJharh2NfHfJvxq8rQfYePUF+HySDwFucYcTdQfN6TyZKdR3D1RqbLsSMrUPBGSaIBVIjGFg24Z9GlAxwDC+BRWZYspx2lAbdQTy/s4p2ikv9k/ohwu5Y84qZ1i23QrDXG/4m9XcxXWFvnvAiUDxl4euFtjuq7xoJWs/g==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
